server:
  port: 9001
jwt:
  config:
    key: xust7202nbxustsbwygz
    ttl: 9999999999999
spring:
  datasource:
#  生产环境
#    username: bhj_noshampoo
#    password: bhj!@#bhj0220
#    url: jdbc:mysql://rm-bp148g30b97b8zkr8eo.mysql.rds.aliyuncs
#    .com:3306/hotel_manager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#  日常环境
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hotel_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xust.hotel.acl_pojo.dbo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
