server:
  port: 9001
jwt:
  config:
    key: xust7202nbxustsbwygz
    ttl: 9999999999999
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hotel_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    timeout: 3000
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xust.hotel.acl_pojo.dbo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    mapUnderscoreToCamelCase: true



